(ns adsb.css.build
  (:require [adsb.css.app :as app]
            [clojure.edn :as edn]
            [clojure.java.io :as io]
            [clojure.string :as str]
            [garden.core :as garden])
  (:import (java.io File)))

(def ^:private out-path "resources/public/app.css")

(def ^:private src-dir "src/css")

(def ^:private preamble
  (str "/* GENERATED by `bb css` (adsb.css.build) — DO NOT EDIT.\n"
       "   The source of truth is src/css/adsb/css/*.clj; start at\n"
       "   adsb.css.app, which is the cascade. Edits here are overwritten. */\n\n"))

(defn render []
  (str preamble (garden/css {:pretty-print? true} app/stylesheet)))

(defn write! []
  (let [css (render)]
    (io/make-parents out-path)
    (spit out-path css)
    (println (format "Wrote %s (%,d bytes)" out-path (count css)))))

(defn- sources []
  (->> (file-seq (io/file src-dir))
       (filter #(.isFile ^File %))
       (filter #(str/ends-with? (.getName ^File %) ".clj"))
       (map (juxt #(.getPath ^File %) #(.lastModified ^File %)))
       (into (sorted-map))))

(defn- ns-decl [path]
  (let [[_ns ns-name & clauses] (edn/read-string (slurp path))
        deps (for [clause clauses
                   :when (and (seq? clause) (= :require (first clause)))
                   spec   (rest clause)
                   :let [dep (cond-> spec (vector? spec) first)]
                   :when (str/starts-with? (str dep) "adsb.css.")]
               dep)]
    {:ns   ns-name
     :path path
     :deps (set deps)}))

(defn- in-dependency-order [paths]
  (loop [pending (remove #(= 'adsb.css.build (:ns %)) (map ns-decl paths))
         loaded  #{}
         ordered []]
    (if (seq pending)
      (let [{ready true blocked false}
            (group-by #(empty? (remove loaded (:deps %))) pending)]
        (when-not (seq ready)
          (throw (ex-info "Dependency cycle among adsb.css namespaces"
                          {:blocked (map :ns blocked)})))
        (recur blocked
               (into loaded (map :ns ready))
               (into ordered (map :path ready))))
      ordered)))

(defn- reload! []
  (run! load-file (in-dependency-order (keys (sources)))))

(defn- watch! []
  (println "Watching" src-dir "— ctrl-c to stop.")
  (loop [seen nil]
    (let [now (sources)]
      (when (not= now seen)
        (try
          (reload!)
          (write!)
          (catch Exception e
            (println "CSS compile failed:" (ex-message e)))))
      (Thread/sleep 250)
      (recur now))))

(defn -main [& args]
  (if (some #{"--watch"} args)
    (watch!)
    (write!)))
