(ns adsb.css.build
  "Compiles adsb.css.app to resources/public/app.css. `bb css`, `bb css:watch`.

  app.css is BUILD OUTPUT — generated, gitignored, and never edited by hand,
  exactly like resources/public/js. The Garden namespaces under src/css are
  the only source of truth for it.

  Garden and this source path are declared in the :css alias, NOT in :paths,
  so neither reaches the production classpath: the uberjar ships the compiled
  app.css and no CSS compiler."
  (:require
    [adsb.css.app :as app]
    [clojure.java.io :as io]
    [garden.core :as garden])
  (:import
    (java.io File)))

(def ^:private out-path "resources/public/app.css")

(def ^:private src-dir "src/css")

(def ^:private preamble
  (str "/* GENERATED by `bb css` (adsb.css.build) — DO NOT EDIT.\n"
       "   The source of truth is src/css/adsb/css/*.clj; start at\n"
       "   adsb.css.app, which is the cascade. Edits here are overwritten. */\n\n"))

(defn render
  "The whole stylesheet as a CSS string. Pure — no I/O, so the suite can hold
  it up to the light."
  []
  (str preamble (garden/css {:pretty-print? true} app/stylesheet)))

(defn write!
  "Render the stylesheet and write it to resources/public/app.css."
  []
  (let [css (render)]
    (io/make-parents out-path)
    (spit out-path css)
    (println (format "Wrote %s (%,d bytes)" out-path (count css)))))

(defn- sources
  "Every Garden source file, with its last-modified stamp — the watch's
  fingerprint of the tree."
  []
  (->> (file-seq (io/file src-dir))
       (filter #(.isFile ^File %))
       (filter #(.endsWith (.getName ^File %) ".clj"))
       (map (juxt #(.getPath ^File %) #(.lastModified ^File %)))
       (into (sorted-map))))

(defn- watch!
  "Recompile on every save under src/css, forever. Polls rather than taking a
  filesystem-watcher dependency: this loop runs beside `shadow-cljs watch` in
  `bb dev` and a quarter-second of latency is beneath notice.

  A broken namespace prints its exception and the loop lives on — a typo must
  not take the watcher down with it."
  []
  (println "Watching" src-dir "— ctrl-c to stop.")
  (loop [seen nil]
    (let [now (sources)]
      (when (not= now seen)
        (try
          ;; :reload-all — the tree below adsb.css.app is what changed, and
          ;; a plain require would hand back the stale namespace.
          (require 'adsb.css.app :reload-all)
          (write!)
          (catch Exception e
            (println "CSS compile failed:" (.getMessage e)))))
      (Thread/sleep 250)
      (recur now))))

(defn -main
  "`clojure -M:css -m adsb.css.build [--watch]`"
  [& args]
  (if (some #{"--watch"} args)
    (watch!)
    (write!)))
